### PR TITLE
docs: update filter_query_text input description

### PR DESCRIPTION
**Pull request by selvats**
## Summary
Update the documentation for the filter_query_text input field. 

## How did you test this change?

Verified that the markdown is correct. 

## Issue

https://lacework.atlassian.net/browse/RAIN-77155

### CODE REVIEW

**Review by afiune — COMMENTED** [review]
You have to update the code https://github.com/lacework/terraform-aws-agentless-scanning/blob/main/variables.tf#L77

And then, run `make terraform-docs` to update the README.

**Comment by selvats** [comment]
> You have to update the code https://github.com/lacework/terraform-aws-agentless-scanning/blob/main/variables.tf#L77
> 
> And then, run `make terraform-docs` to update the README.

Thanks @afiune. Have done as suggested. This is the first time I have updated the Terraform files. Good to learn about the correct process.

**Comment by selvats** [comment]
@afiune, @ammarekbote, @dmurray-lacework, will appreciate if one of you can approve this PR.

**Review by ammarekbote — APPROVED** [review]

**Review by afiune — APPROVED** [review]
Please, try to follow the commit naming convention/standard.

https://github.com/lacework/terraform-aws-agentless-scanning/blob/main/DEVELOPER_GUIDELINES.md#commit-message-standard

**Comment by afiune** [comment]
We won't be able to merge this until you sign your commits:

https://github.com/lacework/terraform-aws-agentless-scanning/blob/main/DEVELOPER_GUIDELINES.md#signing-commits

> Signed commits are required for any contribution to this project. Please see Github's documentation on configuring signed commits, [tell git about your signing key](https://docs.github.com/en/github/authenticating-to-github/managing-commit-signature-verification/telling-git-about-your-signing-key) and [signing commits](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits)

**Comment by selvats** [comment]
Closing this PR as I messed up something in the branch.

**Pull request closed without merging**
